version: '3.9'

services:
  web:
      build: .
      command: sh -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"

      volumes:
        - static_volume:/usr/src/app/static
        - media_volume:/usr/src/app/media
      ports:
        - "8000:8000"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: iskender
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations &&
             python3 manage.py migrate"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A config worker -l INFO
    depends_on:
      - web
      - redis
      - migration

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume: